# App Name
spring.application.name=OnlineExpenseTracker

# DataSource Configuration (JDBC URL must start with jdbc:)
spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=oHohdcpecgIylSnbdESTxjemrrYXlqoE




# JSP View Resolver
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
